# Generated by Django 3.2.12 on 2022-02-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type_cs',
            field=models.CharField(choices=[('customer', 'customer'), ('supplier', 'supplier')], default='customer', max_length=100),
        ),
    ]
