# Generated by Django 3.2.12 on 2022-02-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_type_cs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ntn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='strn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
